name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: Convertedin_testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, mysql
        ini-values: post_max_size=256M, upload_max_filesize=256M, max_execution_time=300
        coverage: none

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Generate application key
      run: php artisan key:generate

    - name: Create database
      run: mysql --user=root --password=root --host=127.0.0.1 --execute="CREATE DATABASE IF NOT EXISTS Convertedin_testing;"

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run tests
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: Convertedin_testing
        DB_USERNAME: root
        DB_PASSWORD: password
      run: php artisan test
